# Generated by Django 5.2.1 on 2025-07-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0014_remove_project_assigned_group_and_more"),
        ("teacher", "0003_module_approved_at_module_approved_by_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studentgroup",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="studentgroup",
            name="assignment",
        ),
        migrations.RemoveField(
            model_name="studentgroup",
            name="chosen_option",
        ),
        migrations.RemoveField(
            model_name="studentgroup",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="studentgroup",
            name="members",
        ),
        migrations.RemoveField(
            model_name="projectassignment",
            name="group_formation_deadline",
        ),
        migrations.RemoveField(
            model_name="projectassignment",
            name="is_group_work",
        ),
        migrations.RemoveField(
            model_name="projectassignment",
            name="max_group_size",
        ),
        migrations.RemoveField(
            model_name="projectassignment",
            name="min_group_size",
        ),
        migrations.RemoveField(
            model_name="projectoption",
            name="current_groups",
        ),
        migrations.RemoveField(
            model_name="projectoption",
            name="max_groups",
        ),
        migrations.AddField(
            model_name="projectassignment",
            name="is_team_work",
            field=models.BooleanField(
                default=False, help_text="Ce devoir doit-il être fait en équipe?"
            ),
        ),
        migrations.AddField(
            model_name="projectassignment",
            name="max_team_size",
            field=models.IntegerField(
                default=1, help_text="Taille maximale de l'équipe"
            ),
        ),
        migrations.AddField(
            model_name="projectassignment",
            name="min_team_size",
            field=models.IntegerField(
                default=1, help_text="Taille minimale de l'équipe"
            ),
        ),
        migrations.AddField(
            model_name="projectoption",
            name="current_teams",
            field=models.IntegerField(
                default=0, help_text="Current number of teams assigned"
            ),
        ),
        migrations.AddField(
            model_name="projectoption",
            name="max_teams",
            field=models.IntegerField(
                default=1, help_text="Maximum teams if not unique"
            ),
        ),
        migrations.AlterField(
            model_name="directstudentassignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("assigned", "Assigné"),
                    ("started", "Commencé"),
                    ("submitted", "Soumis"),
                    ("validated", "Validé"),
                ],
                default="assigned",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="projectassignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="projectoption",
            name="is_unique",
            field=models.BooleanField(
                default=True, help_text="Only one team can choose this project"
            ),
        ),
        migrations.DeleteModel(
            name="GroupInvitation",
        ),
        migrations.DeleteModel(
            name="StudentGroup",
        ),
    ]
