# Generated by Django 5.2.1 on 2025-07-08 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0004_alter_studentgroup_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="module",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="module",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="module",
            name="requires_approval",
        ),
    ]
