# Generated by Django 5.2.1 on 2026-07-03 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0015_alter_project_status_deliverablecomment"),
        (
            "teacher",
            "0005_remove_module_approved_at_remove_module_approved_by_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, help_text="Note globale sur 20", max_digits=4
                    ),
                ),
                (
                    "comments",
                    models.TextField(blank=True, help_text="Appréciation générale"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation",
                        to="student.project",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluations",
                        to="teacher.teacherprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Evaluation",
                "verbose_name_plural": "Project Evaluations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="EvaluationCriterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, help_text="Note sur 20", max_digits=4
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="teacher.projectevaluation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluation Criterion",
                "verbose_name_plural": "Evaluation Criteria",
                "ordering": ["order", "id"],
            },
        ),
    ]
