# Generated by Django 5.2.1 on 2026-07-03 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0006_projectevaluation_evaluationcriterion"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuleAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="teacher.module",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="announcements",
                        to="teacher.teacherprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Module Announcement",
                "verbose_name_plural": "Module Announcements",
                "ordering": ["-created_at"],
            },
        ),
    ]
