# Generated by Django 5.2.1 on 2025-05-07 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("stage_initiation", "Stage d'initiation (3ème année)"),
                            (
                                "stage_ingenieur",
                                "Stage d'ingénieur adjoint (4ème année)",
                            ),
                            ("stage_pfe", "Stage de fin d'études - PFE (5ème année)"),
                            ("module", "Projet de module"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "module_or_company",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("technologies", models.CharField(blank=True, max_length=500)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("submitted", "Soumis"),
                            ("in_progress", "En cours"),
                            ("completed", "Complété"),
                            ("pending_validation", "En attente de validation"),
                            ("validated", "Validé"),
                            ("rejected", "Rejeté"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collaborators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="collaborated_projects",
                        to="student.studentprofile",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="student.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectDeliverable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="deliverables/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("report", "Rapport"),
                            ("presentation", "Présentation"),
                            ("source_code", "Code source"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliverables",
                        to="student.project",
                    ),
                ),
            ],
        ),
    ]
