# Generated by Django 5.2.1 on 2025-05-31 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0006_projectmilestone_completed_at_and_more"),
    ]

    operations = []
