# Generated by Django 5.2.1 on 2025-06-01 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0007_update_project_statuses"),
        ("teacher", "0002_module_moduleassignment_moduleenrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="module",
            field=models.ForeignKey(
                blank=True,
                help_text="Module associé à ce projet",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="teacher.module",
            ),
        ),
    ]
