# Generated by Django 5.2.1 on 2025-06-06 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0009_alter_projectcomment_author"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShowcaseTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "color",
                    models.CharField(
                        default="#007bff", help_text="Hex color code", max_length=7
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="is_hidden_by_admin",
            field=models.BooleanField(
                default=False, help_text="Hidden due to reports/violations"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="is_public",
            field=models.BooleanField(
                default=False, help_text="Project is visible on public showcase"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="is_reported",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="made_public_at",
            field=models.DateTimeField(
                blank=True, help_text="When project was made public", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="public_cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Cover image for public display (optional)",
                null=True,
                upload_to="project_covers/",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="public_demo_url",
            field=models.URLField(blank=True, help_text="Live demo link"),
        ),
        migrations.AddField(
            model_name="project",
            name="public_description",
            field=models.TextField(
                blank=True,
                help_text="Public description (falls back to main description if empty)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="public_github_url",
            field=models.URLField(blank=True, help_text="GitHub repository"),
        ),
        migrations.AddField(
            model_name="project",
            name="public_portfolio_url",
            field=models.URLField(blank=True, help_text="Portfolio/project page"),
        ),
        migrations.AddField(
            model_name="project",
            name="report_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="projectactivity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("created", "Création du projet"),
                    ("status_changed", "Changement de statut"),
                    ("collaborator_added", "Ajout de collaborateur"),
                    ("collaborator_removed", "Retrait de collaborateur"),
                    ("milestone_added", "Ajout de jalon"),
                    ("milestone_completed", "Jalon complété"),
                    ("deliverable_added", "Ajout de livrable"),
                    ("made_public", "Projet rendu public"),
                    ("made_private", "Projet retiré du public"),
                    ("comment_added", "Commentaire ajouté"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ProjectView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_views",
                        to="student.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-viewed_at"],
            },
        ),
        migrations.CreateModel(
            name="PublicProjectComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_edited", models.BooleanField(default=False)),
                ("is_flagged", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_comments",
                        to="student.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_likes",
                        to="student.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liked_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("project", "user")},
            },
        ),
        migrations.CreateModel(
            name="ProjectReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("inappropriate", "Contenu inapproprié"),
                            ("spam", "Spam"),
                            ("copyright", "Violation de droits d'auteur"),
                            ("false_info", "Informations fausses"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description détaillée du problème"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_reviewed", models.BooleanField(default=False)),
                ("admin_notes", models.TextField(blank=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="student.project",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "reporter")},
            },
        ),
        migrations.CreateModel(
            name="ProjectShowcaseTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="showcase_tags",
                        to="student.project",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.showcasetag",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "tag")},
            },
        ),
    ]
