# Generated by Django 5.2.1 on 2025-06-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0010_showcasetag_project_is_hidden_by_admin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="bio",
            field=models.TextField(
                blank=True, help_text="Tell us about yourself", null=True
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="github_url",
            field=models.URLField(
                blank=True, help_text="GitHub profile URL", null=True
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="linkedin_url",
            field=models.URLField(
                blank=True, help_text="LinkedIn profile URL", null=True
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="personal_website",
            field=models.URLField(
                blank=True, help_text="Personal website or portfolio", null=True
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="phone_number",
            field=models.CharField(
                blank=True, help_text="Your contact number", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Profile photo",
                null=True,
                upload_to="profile_pics/",
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="profile_updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
