# Generated by Django 5.2.1 on 2025-06-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0011_studentprofile_bio_studentprofile_github_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_notifications", models.BooleanField(default=True)),
                ("project_notifications", models.BooleanField(default=True)),
                ("collaboration_notifications", models.BooleanField(default=True)),
                ("assignment_notifications", models.BooleanField(default=True)),
                ("assignment_reminders", models.BooleanField(default=True)),
                ("group_notifications", models.BooleanField(default=True)),
                (
                    "theme_preference",
                    models.CharField(
                        choices=[
                            ("light", "Clair"),
                            ("dark", "Sombre"),
                            ("auto", "Automatique"),
                        ],
                        default="auto",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
