# Generated by Django 5.2.1 on 2025-06-21 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0012_userpreferences"),
        ("teacher", "0003_module_approved_at_module_approved_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="project_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="teacher.projectassignment",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="assigned_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_projects",
                to="teacher.studentgroup",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="assigned_students",
            field=models.ManyToManyField(
                blank=True,
                help_text="Students directly assigned to this project by teacher",
                related_name="directly_assigned_projects",
                to="student.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="assignment_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="assignment_source",
            field=models.CharField(
                choices=[
                    ("student_initiated", "Student Initiated"),
                    ("teacher_assigned", "Teacher Assigned"),
                ],
                default="student_initiated",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="assignment_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="project_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submitted_projects",
                to="teacher.projectassignment",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="selected_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_projects",
                to="teacher.projectoption",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("invitation", "Invitation de collaboration"),
                    ("project_update", "Mise à jour du projet"),
                    ("milestone", "Jalon ajouté"),
                    ("deliverable", "Livrable ajouté"),
                    ("assignment_created", "Nouveau devoir assigné"),
                    ("assignment_deadline", "Rappel de date limite"),
                    ("group_invitation", "Invitation de groupe"),
                    ("project_selection", "Sélection de projet"),
                    ("assignment_feedback", "Commentaire sur devoir"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="student.project",
            ),
        ),
        migrations.AlterField(
            model_name="projectactivity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("created", "Création du projet"),
                    ("status_changed", "Changement de statut"),
                    ("collaborator_added", "Ajout de collaborateur"),
                    ("collaborator_removed", "Retrait de collaborateur"),
                    ("milestone_added", "Ajout de jalon"),
                    ("milestone_completed", "Jalon complété"),
                    ("deliverable_added", "Ajout de livrable"),
                    ("made_public", "Projet rendu public"),
                    ("made_private", "Projet retiré du public"),
                    ("comment_added", "Commentaire ajouté"),
                    ("assignment_created", "Devoir créé depuis assignation"),
                    ("assignment_submitted", "Devoir soumis"),
                    ("assignment_validated", "Devoir validé"),
                    ("assignment_rejected", "Devoir rejeté"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
