# Generated by Django 5.2.1 on 2025-07-05 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0013_notification_project_assignment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="assigned_group",
        ),
        migrations.RemoveField(
            model_name="project",
            name="assigned_students",
        ),
    ]
