# Generated by Django 5.2.1 on 2026-06-10 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0014_remove_project_assigned_group_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "En cours"),
                    ("submitted", "Soumis"),
                    ("revision_requested", "Révision demandée"),
                    ("validated", "Validé"),
                    ("rejected", "Rejeté"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DeliverableComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deliverable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_comments",
                        to="student.projectdeliverable",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
