# Generated by Django 5.2.1 on 2026-07-03 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0015_alter_project_status_deliverablecomment"),
        ("teacher", "0006_projectevaluation_evaluationcriterion"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeammateRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True,
                        help_text="Compétences, disponibilités, idées de projet...",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teammate_requests",
                        to="teacher.projectassignment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teammate_requests",
                        to="student.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("assignment", "student")},
            },
        ),
    ]
