# Generated by Django 5.2.1 on 2026-07-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0016_teammaterequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("invitation", "Invitation de collaboration"),
                    ("project_update", "Mise à jour du projet"),
                    ("milestone", "Jalon ajouté"),
                    ("deliverable", "Livrable ajouté"),
                    ("assignment_created", "Nouveau devoir assigné"),
                    ("assignment_deadline", "Rappel de date limite"),
                    ("group_invitation", "Invitation de groupe"),
                    ("project_selection", "Sélection de projet"),
                    ("assignment_feedback", "Commentaire sur devoir"),
                    ("announcement", "Annonce de module"),
                ],
                max_length=20,
            ),
        ),
    ]
