# Generated by Django 5.2.1 on 2026-07-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0017_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectdeliverable",
            name="version",
            field=models.PositiveIntegerField(
                default=1, help_text="Version du livrable (v1, v2, ...)"
            ),
        ),
    ]
