# Generated by Django 5.2.1 on 2026-07-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0019_backfill_deliverable_versions"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="email_digest",
            field=models.BooleanField(
                default=False,
                help_text="Recevoir un résumé quotidien au lieu d'un email par événement",
            ),
        ),
    ]
